# Generated by Django 6.0 on 2026-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('secondary_school', 'Secondary School'), ('primary_school', 'Primary School'), ('vocational', 'Vocational/Technical Institution'), ('other', 'Other')], max_length=50)),
                ('student_count', models.CharField(choices=[('below_100', 'Below 100'), ('100_500', '100 - 500'), ('500_1000', '500 - 1,000'), ('1000_5000', '1,000 - 5,000'), ('5000_above', '5,000+')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('challenge', models.CharField(choices=[('manual_collection', 'Manual fee collection processes'), ('tracking', 'Tracking payments and balances'), ('reconciliation', 'Payment reconciliation'), ('communication', 'Communication with students/parents'), ('multiple_systems', 'Multiple disconnected systems'), ('security', 'Data security and protection'), ('reporting', 'Financial reporting'), ('other_challenge', 'Other challenge')], max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (12:00 PM - 4:00 PM)'), ('evening', 'Evening (4:00 PM - 6:00 PM)'), ('flexible', "I'm flexible")], max_length=50)),
                ('include_team', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
