# Generated by Django 6.0.1 on 2026-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('demo_completed', 'Demo Completed'), ('converted', 'Converted')], default='new', max_length=50),
        ),
    ]
